# usage: make prog=cookieClicker
all:
	clang++ -std=c++11 -stdlib=libc++ -o $(prog) $(prog).cpp
	./$(prog) < 1.in 
	./$(prog) < B-small-practice.in > B-small.out
	./$(prog) < B-large-practice.in > B-large.out
