# usage: make prog=cookieClicker
all:
	clang++ -std=c++11 -stdlib=libc++ -o $(prog) $(prog).cpp
	./$(prog) < 1.in 
	./$(prog) < B-small-practice.in > B-small-practice.out 
	./$(prog) < B-large-practice.in > B-large-practice.out 
	#./$(prog) < 6.in > andrzej.out
	# ./$(prog) < A-large.in > A-large.out
